project:
  type: book

book:
  title: "JavaScript Notes"
  author: "Kittipos Sirivongrungson"
  date: today
  repo-url: https://github.com/Lightbridge-KS/js-notes
  site-url: https://js-notes-lightbridge.netlify.app
  chapters:
    - index.qmd
    - part: Node & NPM
      chapters: 
        - "content/node/npm-cheatsheet.qmd"
    - part: JS Basic
      chapters: 
      - "content/basic-syntax.ipynb"
      - "content/datatypes.ipynb"
      - "content/type.ipynb"
      - "content/variable-declare.qmd"
      - "content/operator-arith.qmd"
      - "content/operator-comp.qmd"
      - "content/control-flow.ipynb"
    - part: TS
      chapters: 
      - "content/ts/ts-00-roadmap.qmd"
      - "content/ts/ts-01-getstarted.qmd"
      - "content/ts/ts-02-types-basic.qmd"
    - part: Package
      chapters: 
        - "content/module/01-module-system.qmd"
        - "content/module/02-index-js.qmd"
        - "content/module/03-path-alias.qmd"
    - part: React
      chapters: 
        - "content/react/quick-react-jsx.qmd"
        - "content/react/jsx-deep-dive.qmd"
    - part: Docusaurus
      chapters: 
        - "content/docusaurus/docu-version-system.qmd"
    - part: Next JS
      chapters: 
        - "content/next/creat-next-app.qmd"


format:
  html:
    theme:
      light: 
        - cosmo
        - brand
      dark:
        - darkly

freeze: auto


